//! sqlx-backed `SQLite` implementation of [`RawEventAppendStore`].

use serde_json;
use sqlx::{
	Row, SqlitePool,
	sqlite::{SqliteConnectOptions, SqliteJournalMode, SqlitePoolOptions},
};
use successor_protocol::{
	error::ProtocolViolationCode,
	ids::{EventId, SessionId},
	platform_api::{
		CreateSessionRequestV0, CreateSessionResponseV0, EventPageV0, RawEventAppendRequestV0,
		RawEventAppendResponseV0,
	},
	raw_event::RawEventV0,
	validation::validate_raw_event_stream,
};

use crate::{
	error::{PlatformError, PlatformResult},
	idempotency::{self, IdempotencyOutcome},
	session,
	store::{
		BoxFuture, RawEventAppendStore, violation_set_to_platform_error, violation_to_platform_error,
	},
};

/// sqlx SQLite-backed implementation of [`RawEventAppendStore`].
///
/// The pool is deliberately capped at a single connection. Slice 0 has no
/// throughput requirement that needs concurrent `SQLite` writers, and a
/// single-connection pool serializes every `append_event`/`create_session`
/// call through one connection -- giving the "single writer transaction"
/// ruling for idempotency-check + seq-allocation + validation + persistence
/// a trivially correct implementation with no `BEGIN IMMEDIATE`/busy-retry
/// logic required. Concurrent callers still exercise real interleaving at
/// the call-site level; they queue for the connection rather than racing
/// inside `SQLite`, which is what actually guarantees dense, gapless
/// `session_seq` allocation under concurrent load.
pub struct SqliteAppendStore {
	pool: SqlitePool,
}

impl SqliteAppendStore {
	/// Opens (creating if missing) a `SQLite` database file at `path` and runs
	/// pending migrations.
	pub async fn connect(path: &str) -> Result<Self, sqlx::Error> {
		let options = SqliteConnectOptions::new()
			.filename(path)
			.create_if_missing(true)
			.journal_mode(SqliteJournalMode::Wal);
		Self::connect_with(options).await
	}

	/// Opens a private in-memory database and runs pending migrations.
	/// Intended for tests.
	pub async fn connect_in_memory() -> Result<Self, sqlx::Error> {
		let options: SqliteConnectOptions = "sqlite::memory:".parse()?;
		Self::connect_with(options).await
	}

	async fn connect_with(options: SqliteConnectOptions) -> Result<Self, sqlx::Error> {
		let pool = SqlitePoolOptions::new()
			.max_connections(1)
			.connect_with(options)
			.await?;
		sqlx::migrate!("./migrations").run(&pool).await?;
		Ok(Self { pool })
	}
}

/// Maps a storage-layer failure into a `PlatformError` without leaking
/// driver detail (file paths, SQL text, `SQLite` error strings) to callers.
/// The original error is still logged for operator diagnosis.
fn sqlx_error(err: sqlx::Error) -> PlatformError {
	tracing::error!(error = %err, "storage operation failed");
	PlatformError::new(ProtocolViolationCode::Internal, "storage operation failed")
}

/// Maps a JSON encode/decode failure on a stored row into a `PlatformError`
/// without leaking the offending payload. The original error is still
/// logged for operator diagnosis.
fn json_error(err: serde_json::Error) -> PlatformError {
	tracing::error!(error = %err, "storage payload serialization failed");
	PlatformError::new(ProtocolViolationCode::Internal, "storage payload serialization failed")
}

/// SQL expression producing the current UTC wall-clock time as an ISO 8601 /
/// RFC 3339 string with millisecond precision. Generated by `SQLite` itself so
/// the platform crate does not need a `chrono`/`time` dependency beyond the
/// `sqlx` bootstrap dependency this lane is authorized to add.
const NOW_EXPR: &str = "strftime('%Y-%m-%dT%H:%M:%fZ','now')";

/// Builds the full, platform-assigned `RawEventV0` for a request that has
/// passed the idempotency check and been assigned `session_seq`. Every field
/// is copied from the client-supplied request except `session_seq` itself,
/// which the request DTO structurally cannot carry.
fn request_to_candidate(request: &RawEventAppendRequestV0, session_seq: u64) -> RawEventV0 {
	RawEventV0 {
		schema_version: request.schema_version.clone(),
		event_id: request.event_id.clone(),
		session_seq,
		idempotency_key: request.idempotency_key.clone(),
		event_type: request.event_type.clone(),
		session_id: request.session_id.clone(),
		turn_id: request.turn_id.clone(),
		request_id: request.request_id.clone(),
		occurred_at: request.occurred_at.clone(),
		producer: request.producer.clone(),
		causation_event_id: request.causation_event_id.clone(),
		correlation_id: request.correlation_id.clone(),
		entity_ids: request.entity_ids.clone(),
		visibility: request.visibility.clone(),
		redaction: request.redaction.clone(),
		payload: request.payload.clone(),
		artifact: request.artifact.clone(),
	}
}

impl RawEventAppendStore for SqliteAppendStore {
	fn create_session(
		&self,
		request: CreateSessionRequestV0,
	) -> BoxFuture<'_, PlatformResult<CreateSessionResponseV0>> {
		Box::pin(async move {
			let session_id = session::new_session_id();
			let workspace_json = serde_json::to_string(&request.workspace).map_err(json_error)?;
			let created_by_json = serde_json::to_string(&request.created_by).map_err(json_error)?;

			let mut conn = self.pool.acquire().await.map_err(sqlx_error)?;
			let sql = format!(
				"INSERT INTO sessions (session_id, workspace_json, title, created_by_json, \
				 created_at, last_session_seq) VALUES (?, ?, ?, ?, {NOW_EXPR}, 0) RETURNING created_at"
			);
			let created_at: String = sqlx::query_scalar(&sql)
				.bind(session_id.as_str())
				.bind(&workspace_json)
				.bind(&request.title)
				.bind(&created_by_json)
				.fetch_one(&mut *conn)
				.await
				.map_err(sqlx_error)?;

			Ok(CreateSessionResponseV0 { session_id, created_at })
		})
	}

	fn append_event(
		&self,
		request: RawEventAppendRequestV0,
	) -> BoxFuture<'_, PlatformResult<RawEventAppendResponseV0>> {
		Box::pin(async move {
			let candidate_fingerprint =
				idempotency::fingerprint(&request).map_err(violation_to_platform_error)?;

			let mut tx = self.pool.begin().await.map_err(sqlx_error)?;

			let session_exists = sqlx::query("SELECT 1 FROM sessions WHERE session_id = ?")
				.bind(request.session_id.as_str())
				.fetch_optional(&mut *tx)
				.await
				.map_err(sqlx_error)?;
			if session_exists.is_none() {
				return Err(PlatformError::new(
					ProtocolViolationCode::NotFound,
					format!("session {} not found", request.session_id),
				));
			}

			if let Some(row) = sqlx::query(
				"SELECT fingerprint, response_json FROM idempotency_keys WHERE session_id = ? AND \
				 idempotency_key = ?",
			)
			.bind(request.session_id.as_str())
			.bind(&request.idempotency_key)
			.fetch_optional(&mut *tx)
			.await
			.map_err(sqlx_error)?
			{
				let stored_fingerprint: String = row.try_get("fingerprint").map_err(sqlx_error)?;
				let response_json: String = row.try_get("response_json").map_err(sqlx_error)?;

				return match idempotency::classify(&stored_fingerprint, &candidate_fingerprint) {
					IdempotencyOutcome::Replay => {
						let mut response: RawEventAppendResponseV0 =
							serde_json::from_str(&response_json).map_err(json_error)?;
						response.duplicate = true;
						tx.commit().await.map_err(sqlx_error)?;
						Ok(response)
					},
					IdempotencyOutcome::Conflict => Err(PlatformError::new(
						ProtocolViolationCode::DuplicateIdempotencyKey,
						format!(
							"idempotency_key {} was already used in session {} with a different request",
							request.idempotency_key, request.session_id
						),
					)),
				};
			}

			let event_id_taken = sqlx::query("SELECT 1 FROM raw_events WHERE event_id = ?")
				.bind(request.event_id.as_str())
				.fetch_optional(&mut *tx)
				.await
				.map_err(sqlx_error)?;
			if event_id_taken.is_some() {
				return Err(PlatformError::new(
					ProtocolViolationCode::Conflict,
					format!("event_id {} is already in use", request.event_id),
				));
			}

			let next_seq: i64 = sqlx::query_scalar(
				"UPDATE sessions SET last_session_seq = last_session_seq + 1 WHERE session_id = ? \
				 RETURNING last_session_seq",
			)
			.bind(request.session_id.as_str())
			.fetch_one(&mut *tx)
			.await
			.map_err(sqlx_error)?;
			let session_seq = u64::try_from(next_seq).map_err(|_| {
				PlatformError::new(ProtocolViolationCode::Internal, "sequence allocation overflow")
			})?;

			let history_rows = sqlx::query(
				"SELECT event_json FROM raw_events WHERE session_id = ? ORDER BY session_seq ASC",
			)
			.bind(request.session_id.as_str())
			.fetch_all(&mut *tx)
			.await
			.map_err(sqlx_error)?;
			let mut events: Vec<RawEventV0> = Vec::with_capacity(history_rows.len() + 1);
			for row in &history_rows {
				let json: String = row.try_get("event_json").map_err(sqlx_error)?;
				events.push(serde_json::from_str(&json).map_err(json_error)?);
			}

			let candidate = request_to_candidate(&request, session_seq);
			candidate
				.validate_structure()
				.map_err(violation_to_platform_error)?;
			events.push(candidate.clone());
			validate_raw_event_stream(&events).map_err(violation_set_to_platform_error)?;

			let event_json = serde_json::to_string(&candidate).map_err(json_error)?;
			let stored_at: String = sqlx::query_scalar(&format!("SELECT {NOW_EXPR}"))
				.fetch_one(&mut *tx)
				.await
				.map_err(sqlx_error)?;

			sqlx::query(
				"INSERT INTO raw_events (event_id, session_id, session_seq, idempotency_key, \
				 event_json, stored_at) VALUES (?, ?, ?, ?, ?, ?)",
			)
			.bind(candidate.event_id.as_str())
			.bind(candidate.session_id.as_str())
			.bind(session_seq as i64)
			.bind(&candidate.idempotency_key)
			.bind(&event_json)
			.bind(&stored_at)
			.execute(&mut *tx)
			.await
			.map_err(sqlx_error)?;

			let response = RawEventAppendResponseV0 {
				event_id: candidate.event_id.clone(),
				session_seq,
				duplicate: false,
				stored_at,
				source_envelope_id: candidate.entity_ids.source_envelope_id.clone(),
				artifact_id: candidate.entity_ids.artifact_id.clone(),
			};
			let response_json = serde_json::to_string(&response).map_err(json_error)?;

			sqlx::query(
				"INSERT INTO idempotency_keys (session_id, idempotency_key, fingerprint, event_id, \
				 response_json) VALUES (?, ?, ?, ?, ?)",
			)
			.bind(candidate.session_id.as_str())
			.bind(&candidate.idempotency_key)
			.bind(&candidate_fingerprint)
			.bind(candidate.event_id.as_str())
			.bind(&response_json)
			.execute(&mut *tx)
			.await
			.map_err(sqlx_error)?;

			tx.commit().await.map_err(sqlx_error)?;

			Ok(response)
		})
	}

	fn read_event<'a>(
		&'a self,
		event_id: &'a EventId,
	) -> BoxFuture<'a, PlatformResult<Option<RawEventV0>>> {
		Box::pin(async move {
			let mut conn = self.pool.acquire().await.map_err(sqlx_error)?;
			let row = sqlx::query("SELECT event_json FROM raw_events WHERE event_id = ?")
				.bind(event_id.as_str())
				.fetch_optional(&mut *conn)
				.await
				.map_err(sqlx_error)?;
			match row {
				Some(row) => {
					let json: String = row.try_get("event_json").map_err(sqlx_error)?;
					let event: RawEventV0 = serde_json::from_str(&json).map_err(json_error)?;
					Ok(Some(event))
				},
				None => Ok(None),
			}
		})
	}

	fn read_session_events<'a>(
		&'a self,
		session_id: &'a SessionId,
		after_seq: u64,
		limit: u32,
	) -> BoxFuture<'a, PlatformResult<EventPageV0>> {
		Box::pin(async move {
			let mut conn = self.pool.acquire().await.map_err(sqlx_error)?;

			let session_exists = sqlx::query("SELECT 1 FROM sessions WHERE session_id = ?")
				.bind(session_id.as_str())
				.fetch_optional(&mut *conn)
				.await
				.map_err(sqlx_error)?;
			if session_exists.is_none() {
				return Err(PlatformError::new(
					ProtocolViolationCode::NotFound,
					format!("session {session_id} not found"),
				));
			}

			let fetch_limit = i64::from(limit) + 1;
			let after_seq_i64 = i64::try_from(after_seq).unwrap_or(i64::MAX);
			let rows = sqlx::query(
				"SELECT event_json, session_seq FROM raw_events WHERE session_id = ? AND session_seq \
				 > ? ORDER BY session_seq ASC LIMIT ?",
			)
			.bind(session_id.as_str())
			.bind(after_seq_i64)
			.bind(fetch_limit)
			.fetch_all(&mut *conn)
			.await
			.map_err(sqlx_error)?;

			let has_more = i64::try_from(rows.len()).unwrap_or(i64::MAX) > i64::from(limit);
			let limit_usize = limit as usize;
			let mut events = Vec::with_capacity(rows.len().min(limit_usize));
			let mut next_after_seq = after_seq;
			for row in rows.into_iter().take(limit_usize) {
				let json: String = row.try_get("event_json").map_err(sqlx_error)?;
				let seq: i64 = row.try_get("session_seq").map_err(sqlx_error)?;
				next_after_seq = u64::try_from(seq).unwrap_or(next_after_seq);
				events.push(serde_json::from_str(&json).map_err(json_error)?);
			}

			Ok(EventPageV0::new(session_id.clone(), events, next_after_seq, has_more))
		})
	}
}

#[cfg(test)]
mod tests {
	use successor_protocol::ids::SessionId;

	use super::*;

	async fn store_with_session() -> (SqliteAppendStore, SessionId) {
		let store = SqliteAppendStore::connect_in_memory()
			.await
			.expect("in-memory store connects");
		let request = CreateSessionRequestV0 {
			workspace:  successor_protocol::platform_api::WorkspaceV0 {
				id:        "ws_test".to_string(),
				label:     "test workspace".to_string(),
				root_hint: "/tmp/ws".to_string(),
			},
			title:      "test session".to_string(),
			created_by: successor_protocol::platform_api::CreatedByV0 {
				client_kind: "cli".to_string(),
				client_id:   "tester".to_string(),
			},
		};
		let response = store
			.create_session(request)
			.await
			.expect("session creation succeeds");
		(store, response.session_id)
	}

	fn append_request(
		session_id: &str,
		event_id: &str,
		idempotency_key: &str,
		causation_event_id: Option<&str>,
		payload: serde_json::Value,
	) -> RawEventAppendRequestV0 {
		let value = serde_json::json!({
			"schema_version": "platform.raw_event.v0",
			"event_id": event_id,
			"idempotency_key": idempotency_key,
			"event_type": "tool_catalog.published",
			"session_id": session_id,
			"turn_id": null,
			"request_id": "req_test",
			"occurred_at": "2026-06-23T12:00:00Z",
			"producer": { "kind": "kernel", "id": "local-dev-kernel" },
			"causation_event_id": causation_event_id,
			"correlation_id": "req_test",
			"entity_ids": {
				"message_id": null, "tool_call_id": null, "source_envelope_id": null,
				"artifact_id": null, "assemble_id": null, "context_item_ids": [],
				"trace_id": null, "error_id": null, "provider_event_id": null
			},
			"visibility": { "model": true, "transcript": false, "recall": false, "assemble": false, "share": false, "debug": true },
			"redaction": "public",
			"payload": payload,
			"artifact": null
		});
		serde_json::from_value(value).expect("valid append request fixture")
	}

	#[tokio::test]
	async fn first_event_in_session_gets_seq_one() {
		let (store, session_id) = store_with_session().await;
		let request = append_request(
			session_id.as_str(),
			"evt_first",
			"idem-first",
			None,
			serde_json::json!({ "k": "v" }),
		);
		let response = store.append_event(request).await.expect("append succeeds");
		assert_eq!(response.session_seq, 1);
		assert!(!response.duplicate);
	}

	#[tokio::test]
	async fn dense_seq_under_sequential_appends() {
		let (store, session_id) = store_with_session().await;
		for i in 1..=5u64 {
			let request = append_request(
				session_id.as_str(),
				&format!("evt_seq_{i}"),
				&format!("idem-seq-{i}"),
				None,
				serde_json::json!({ "i": i }),
			);
			let response = store.append_event(request).await.expect("append succeeds");
			assert_eq!(response.session_seq, i);
		}
	}

	#[tokio::test]
	async fn dense_seq_under_concurrent_appends() {
		let store = std::sync::Arc::new(
			SqliteAppendStore::connect_in_memory()
				.await
				.expect("in-memory store connects"),
		);
		let request = CreateSessionRequestV0 {
			workspace:  successor_protocol::platform_api::WorkspaceV0 {
				id:        "ws_test".to_string(),
				label:     "test".to_string(),
				root_hint: "/tmp".to_string(),
			},
			title:      "concurrent".to_string(),
			created_by: successor_protocol::platform_api::CreatedByV0 {
				client_kind: "cli".to_string(),
				client_id:   "tester".to_string(),
			},
		};
		let session_id = store
			.create_session(request)
			.await
			.expect("session creation succeeds")
			.session_id;

		let mut handles = Vec::new();
		for i in 1..=10u64 {
			let store = std::sync::Arc::clone(&store);
			let session_id = session_id.as_str().to_string();
			handles.push(tokio::spawn(async move {
				let request = append_request(
					&session_id,
					&format!("evt_conc_{i}"),
					&format!("idem-conc-{i}"),
					None,
					serde_json::json!({ "i": i }),
				);
				store
					.append_event(request)
					.await
					.expect("append succeeds")
					.session_seq
			}));
		}

		let mut seqs: Vec<u64> = Vec::new();
		for handle in handles {
			seqs.push(handle.await.expect("task does not panic"));
		}
		seqs.sort_unstable();
		assert_eq!(seqs, (1..=10u64).collect::<Vec<_>>());
	}

	#[tokio::test]
	async fn byte_identical_replay_returns_duplicate_true_without_new_seq() {
		let (store, session_id) = store_with_session().await;
		let request = append_request(
			session_id.as_str(),
			"evt_replay",
			"idem-replay",
			None,
			serde_json::json!({ "k": "v" }),
		);
		let first = store
			.append_event(request.clone())
			.await
			.expect("first append succeeds");
		assert!(!first.duplicate);
		assert_eq!(first.session_seq, 1);

		let replay = store.append_event(request).await.expect("replay succeeds");
		assert!(replay.duplicate);
		assert_eq!(replay.session_seq, 1);
		assert_eq!(replay.event_id, first.event_id);

		let page = store
			.read_session_events(&session_id, 0, 10)
			.await
			.expect("read succeeds");
		assert_eq!(page.events.len(), 1, "replay must not allocate a second event");
	}

	#[tokio::test]
	async fn same_key_different_payload_returns_duplicate_idempotency_key_conflict() {
		let (store, session_id) = store_with_session().await;
		let first = append_request(
			session_id.as_str(),
			"evt_a",
			"idem-shared",
			None,
			serde_json::json!({ "k": "v1" }),
		);
		store
			.append_event(first)
			.await
			.expect("first append succeeds");

		let second = append_request(
			session_id.as_str(),
			"evt_b",
			"idem-shared",
			None,
			serde_json::json!({ "k": "v2" }),
		);
		let err = store
			.append_event(second)
			.await
			.expect_err("conflicting payload is rejected");
		assert!(err.to_string().starts_with("duplicate_idempotency_key:"), "unexpected error: {err}");

		let page = store
			.read_session_events(&session_id, 0, 10)
			.await
			.expect("read succeeds");
		assert_eq!(page.events.len(), 1, "conflicting request must not allocate a sequence");
	}

	#[tokio::test]
	async fn cross_session_causation_rejected() {
		let (store, session_a) = store_with_session().await;
		let create_b = CreateSessionRequestV0 {
			workspace:  successor_protocol::platform_api::WorkspaceV0 {
				id:        "ws_test".to_string(),
				label:     "test".to_string(),
				root_hint: "/tmp".to_string(),
			},
			title:      "session b".to_string(),
			created_by: successor_protocol::platform_api::CreatedByV0 {
				client_kind: "cli".to_string(),
				client_id:   "tester".to_string(),
			},
		};
		let session_b = store
			.create_session(create_b)
			.await
			.expect("second session creation succeeds")
			.session_id;

		let in_b = append_request(
			session_b.as_str(),
			"evt_in_session_b",
			"idem-in-session-b",
			None,
			serde_json::json!({ "k": "v" }),
		);
		store
			.append_event(in_b)
			.await
			.expect("append into session b succeeds");

		// `evt_in_session_b` is a real, persisted event, but it belongs to a
		// different session; causation must not resolve across sessions.
		let request = append_request(
			session_a.as_str(),
			"evt_bad_causation",
			"idem-bad-causation",
			Some("evt_in_session_b"),
			serde_json::json!({ "k": "v" }),
		);
		let err = store
			.append_event(request)
			.await
			.expect_err("cross-session causation is rejected");
		assert!(err.to_string().starts_with("causation_violation:"), "unexpected error: {err}");

		let page = store
			.read_session_events(&session_a, 0, 10)
			.await
			.expect("read succeeds");
		assert_eq!(page.events.len(), 0, "rejected append must not leave a partial row");
	}

	#[tokio::test]
	async fn future_causation_rejected() {
		let (store, session_id) = store_with_session().await;
		let first = append_request(
			session_id.as_str(),
			"evt_future_1",
			"idem-future-1",
			None,
			serde_json::json!({ "k": "v" }),
		);
		store
			.append_event(first)
			.await
			.expect("first append succeeds");

		// References its own event_id, which cannot be a strictly earlier event.
		let request = append_request(
			session_id.as_str(),
			"evt_future_2",
			"idem-future-2",
			Some("evt_future_2"),
			serde_json::json!({ "k": "v" }),
		);
		let err = store
			.append_event(request)
			.await
			.expect_err("self/future causation is rejected");
		let message = err.to_string();
		assert!(
			message.starts_with("causation_violation:") || message.starts_with("future_reference:"),
			"unexpected error: {message}"
		);

		let page = store
			.read_session_events(&session_id, 0, 10)
			.await
			.expect("read succeeds");
		assert_eq!(page.events.len(), 1, "only the first, valid event is persisted");
	}

	#[tokio::test]
	async fn credential_looking_payload_rejected() {
		let (store, session_id) = store_with_session().await;
		let request = append_request(
			session_id.as_str(),
			"evt_cred",
			"idem-cred",
			None,
			serde_json::json!({ "api_key": "sk-ant-api03-not-a-real-key" }),
		);
		let err = store
			.append_event(request)
			.await
			.expect_err("credential-looking payload is rejected");
		assert!(err.to_string().starts_with("credential_leakage:"), "unexpected error: {err}");

		let page = store
			.read_session_events(&session_id, 0, 10)
			.await
			.expect("read succeeds");
		assert_eq!(page.events.len(), 0, "rejected append must not leave a partial row");
	}

	#[tokio::test]
	async fn rollback_leaves_no_partial_rows_after_validation_failure_mid_transaction() {
		let (store, session_id) = store_with_session().await;
		let good = append_request(
			session_id.as_str(),
			"evt_good",
			"idem-good",
			None,
			serde_json::json!({ "k": "v" }),
		);
		store
			.append_event(good)
			.await
			.expect("first append succeeds");

		let bad = append_request(
			session_id.as_str(),
			"evt_bad",
			"idem-bad",
			Some("evt_does_not_exist"),
			serde_json::json!({ "k": "v" }),
		);
		store
			.append_event(bad)
			.await
			.expect_err("invalid causation is rejected");

		// The failed append must not have allocated a sequence, inserted a raw
		// event row, or inserted an idempotency-key row: a subsequent valid
		// append gets seq 2 (not 3), and only two events are ever readable.
		let next = append_request(
			session_id.as_str(),
			"evt_next",
			"idem-next",
			None,
			serde_json::json!({ "k": "v" }),
		);
		let response = store
			.append_event(next)
			.await
			.expect("append after rollback succeeds");
		assert_eq!(
			response.session_seq, 2,
			"rolled-back attempt must not have consumed a sequence number"
		);

		let page = store
			.read_session_events(&session_id, 0, 10)
			.await
			.expect("read succeeds");
		assert_eq!(page.events.len(), 2);
	}

	#[tokio::test]
	async fn unknown_fields_at_append_boundary_rejected() {
		let json = serde_json::json!({
			"schema_version": "platform.raw_event.v0",
			"event_id": "evt_unknown_field",
			"idempotency_key": "idem-unknown-field",
			"event_type": "tool_catalog.published",
			"session_id": "ses_test",
			"turn_id": null,
			"request_id": "req_test",
			"occurred_at": "2026-06-23T12:00:00Z",
			"producer": { "kind": "kernel", "id": "local-dev-kernel" },
			"causation_event_id": null,
			"correlation_id": "req_test",
			"entity_ids": { "message_id": null, "tool_call_id": null, "source_envelope_id": null, "artifact_id": null, "assemble_id": null, "context_item_ids": [], "trace_id": null, "error_id": null, "provider_event_id": null },
			"visibility": { "model": true, "transcript": false, "recall": false, "assemble": false, "share": false, "debug": true },
			"redaction": "public",
			"payload": { "k": "v" },
			"artifact": null,
			"session_seq": 999
		});
		let result: Result<RawEventAppendRequestV0, _> = serde_json::from_value(json);
		assert!(
			result.is_err(),
			"a client-supplied session_seq must be rejected as an unknown field, not silently \
			 accepted"
		);
	}
}
